version: '3.7'

services:
  postgres-todolist:
    image: postgres:12
    environment:
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_DB=todolist
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq-todolist:
    init: true
    hostname: rabbitmq
    image: rabbitmq:3.7.15-management
    environment:
      - RABBITMQ_DEFAULT_USER=todolist
      - RABBITMQ_DEFAULT_PASS=todolist
      - RABBITMQ_DEFAULT_VHOST=todolist
    ports:
      - "15672:5672"
    volumes:
      - rdata:/var/lib/rabbitmq
  dramatiq-todolist:
    init: true
    stdin_open: true
    tty: true
    restart: unless-stopped
    image: todolist
    command: dramatiq
    depends_on:
      - django-todolist
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - RABBITMQ_BROKER_URL=amqp://todolist:todolist@rabbitmq-todolist:5672/todolist
      - DATABASE_URL=psql://todolist:todolist@postgres-todolist:5432/todolist
      - NOTIFICATION_KEY=BNtDub86M_KTCNb6zH4L_OamnQoy51BdWd_1DqW6j8SLyBL6BtU4awc8LiEIpsRoQT9e05bwFuuYzeO1c7M7rm8
      - FIREBASE_CREDENTIALS_PATH=/etc/fcm_todolistv2.json

      # silence warnings. be careful!
      - PYTHONWARNINGS=ignore
    volumes:
      - .:/code
      - /opt/fcm_todolistv2.json:/etc/fcm_todolistv2.json
  django-todolist:
    image: todolist
    restart: unless-stopped
    build:
      context: .
    command: django
    volumes:
      - .:/code
      - dmedia:/media
      - dstatic:/static
      - /opt/fcm_todolistv2.json:/etc/fcm_todolistv2.json
    ports:
      - "19000:8000"
    depends_on:
      - postgres-todolist
      - rabbitmq-todolist
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - RABBITMQ_BROKER_URL=amqp://todolist:todolist@rabbitmq-todolist:5672/todolist
      - DATABASE_URL=psql://todolist:todolist@postgres-todolist:5432/todolist
      - NOTIFICATION_KEY=BNtDub86M_KTCNb6zH4L_OamnQoy51BdWd_1DqW6j8SLyBL6BtU4awc8LiEIpsRoQT9e05bwFuuYzeO1c7M7rm8
      - FIREBASE_CREDENTIALS_PATH=/etc/fcm_todolistv2.json

networks:
  default:
    name: todolist_default
    external:
      true

volumes:
  pgdata:
  rdata:
  mdata:
  dmedia:
  dstatic: